server:
  port: 8001

mybatis:
  config-location: classpath:mybatis-config.xml   #mybatis的主配置文件
spring:
  application:
    name: woniu58-provider  #当前项目名，微服务的名字   非常重要，做集群时名字一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 指定连接书库的类名
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password:
    dbcp2:
      min-idle: 5   #连接池最小连接数
      initial-size: 5 #初始化大小
      max-total: 10 #最大连接数
      max-wait-millis: 200  #最大等待时间
  ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 1200
    #打印sql时的语句
    logging:
      level:
        com:
          acong:
            dao: debug
      file: d:/logs/bsbdj.log

pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql